config/routes.rb
Rails.application.routes.draw do
  resources :books
  root :to => redirect('/books')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    def
        self.all_genres ;["Horror", "Science fiction", "Drama", "Action and Adventure", "Romance", "Mystery" ] ;end #shortcut:array of strings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    
    def show
       id = params[:id]
       @book = Book.find(id)
    end
    
    def index
                
        if !params.key?(:genres)
            params[:genres] = {}
        end
        permitted = params.permit(:sort, genres: params[:genres].keys)
        sort = permitted[:sort] || session[:sort]
      
        case sort
            when 'title'
                ordering,@title_header = {:title => :asc}, 'hilite'
            when 'publish_date'      
                ordering,@date_header = {:publish_date => :asc}, 'hilite'
        end
        
        @all_genres = Book.all_genres  
        @selected_genres = permitted[:genres] || session[:genres] || {}
        if @selected_genres == {}  
          @selected_genres = Hash[@all_genres.map {|genre| [genre, genre]}]
        end
         
        if permitted[:sort] != session[:sort] or permitted[:genres] != session[:genres]
          session[:sort] = sort
          session[:genres] = @selected_genres
          redirect_to :sort => sort, :genres => @selected_genres and return
        end
         
        @books = Book.where(genre: @selected_genres.keys).order(ordering)
    end
    def new
      @book = Book.new
    end
     
    def create
            params.require(:book)
            permitted = params[:book].permit(:title,:author,:genre,:publish_date,:ISBNnum)
            @book = Book.create!(permitted)
        if @book.save
            flash[:notice] = "#{@book.title} was successfully created."
            redirect_to books_path
        else
            render 'new'
        end
    end
     
    def edit
       @book = Book.find params[:id]
    end
    
    def update
       @book = Book.find params[:id]
       params.require(:book)
       permitted = params[:book].permit(:title,:author,:genre,:publish_date,:description, :ISBNnum)
       if @book.update_attributes!(permitted)
       flash[:notice] = "#{@book.title} was successfully updated."
       redirect_to book_path(@book)
       else
       render 'edit' 
       end
    end
    
    def destroy
       @book = Book.find(params[:id])
       @book.destroy
       flash[:notice] = "Book '#{@book.title}' deleted."
       redirect_to books_path
    end
 
   
        
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.haml
%h2 Edit Book

= form_tag book_path(@book), :method => :put do

  = label :book, :title, 'Title'
  = text_field :book, 'title'

  = label :book, :author, 'Author'
  = text_field :book, :author

  = label :book, :genre, 'Genre'
  = select :book, :genre, ['Science fiction','Drama','Action and Adventure','Romance','Mystery','Horror']
 
  = label :book, :publish_date, 'Published On'
  = date_select :book, :publish_date
  
  = label :book, :ISBNnum, 'ISBN number'
  = text_field :book, :ISBNnum

  = label :book, :description, 'Description'
  = text_field :book, :description

  = submit_tag 'Save Changes'

app/views/books/index.html.haml
%h1 All Books

= form_tag books_path, :method => :get, :id => 'genres_form' do
  = hidden_field_tag "title_sort", true if @title_header
  = hidden_field_tag ":published_date_sort", true if @date_header
  Include:
  - @all_genres.each do |genre|
    = genre
    = check_box_tag "genres[#{genre}]", 1, @selected_genres.include?(genre), :id => "genres_#{genre}"
  = submit_tag 'Refresh', :id => 'genres_submit'
 

%table#books
  %thead
    %tr
      %th{:class => @title_header}= link_to 'Books Title', books_path(:sort => 'title', :genres => @selected_genres), :id => 'title_header'
      %th Author
      %th Genre
      %th ISBNnum
      %th{:class => @date_header}= link_to 'Publish Date', books_path(:sort => 'publish_date', :genres => @selected_genres), :id => 'publish_date_header'
      %th More Info
  %tbody
    - @books.each do |book|
      %tr
        %td= book.title 
        %td= book.author 
        %td= book.genre
        %td= book.ISBNnum
        %td= book.publish_date
        %td= link_to "More about #{book.title}", book_path(book)
 
= link_to 'Add new book', new_book_path

app/views/books/new.html.haml
%h2 Create New Book

= form_tag books_path, :method => :post do

  = label :book, :title, 'Title'
  = text_field :book, :title

  = label :book, :author, 'Author'
  = text_field :book, :author

  = label :book, :genre, 'Genre'
  = select :book, :genre, ['Science fiction','Drama','Action and Adventure','Romance','Mystery','Horror']
 
  = label :book, :publish_date, 'Published On'
  = date_select :book, :publish_date

  = label :book, :description, 'Description'
  = text_field :book, :description

  = submit_tag 'Save Changes'

app/views/books/show.html.haml
%h2 Details about #{@book.title}

%ul#details
  %li
    Author:
    = @book.author
  %li
    Genre:
    = @book.genre
  %li
    Released on:
    = @book.publish_date.strftime("%B %d, %Y")
  %li
    ISBN number:
    = @book.ISBNnum

%h3 Description:

%p#description= @book.description

= link_to 'Back to book list', books_path
= link_to 'Edit info', edit_book_path(@book)
= link_to 'Delete', book_path(@book), :method => :delete

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFavouriteBooks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

  </body>
</html>